version: "3.9"
services:
  # Microsoft SQL Server 資料庫
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: HW
      MYSQL_USER: bigred
      MYSQL_PASSWORD: bigred
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    volumes:
      - /home/johnny096317/mysql:/docker-entrypoint-initdb.d/

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Taipei

  apache:
    image: php:8.3.1-apache
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: Asia/Taipei
    volumes:
      - /home/johnny096317/www:/var/www/html
